# Generated by Django 5.2.5 on 2025-08-26 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('s3_file_key', models.CharField(help_text='The key/path to the original file in S3', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('PPT', 'Presentation'), ('FLASH', 'Flashcards'), ('MCQ', 'MCQ Set'), ('POD', 'Podcast')], max_length=5)),
                ('s3_url', models.URLField(help_text='Public URL to the generated file in S3', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='projects.project')),
            ],
        ),
    ]
