# Generated by Django 5.2.5 on 2025-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for the generation process', max_length=50, null=True),
        ),
    ]
