# Generated by Django 5.2.5 on 2025-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='s3_file_key',
        ),
        migrations.AddField(
            model_name='project',
            name='uploaded_file',
            field=models.FileField(default='uploads/default.txt', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
