# Generated by Django 5.2.5 on 2025-08-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_s3_file_key_project_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='project',
            name='s3_file_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
