# Generated by Django 5.2.5 on 2025-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_uploaded_file_project_s3_file_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_id',
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='content_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='task_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='s3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='s3_file_key',
            field=models.CharField(max_length=1024),
        ),
    ]
