# Generated by Django 5.2.5 on 2025-08-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_task_id_generatedcontent_content_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='s3_file_key',
            field=models.CharField(default='default_key', max_length=1024),
        ),
    ]
