# Generated by Django 5.2.5 on 2025-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_s3_file_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcontent',
            name='content_data',
        ),
        migrations.AlterField(
            model_name='project',
            name='s3_file_key',
            field=models.CharField(max_length=1024),
        ),
    ]
