# Generated by Django 5.2.5 on 2025-09-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_generatedcontent_content_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generatedcontent',
            unique_together={('project', 'content_type')},
        ),
    ]
